= ec track bundle

Record tracking information about Tekton bundles== Synopsis

Record tracking information about Tekton bundles

Each Tekton Bundle is expected to be a proper OCI image reference. They
may contain a tag, a digest, or both. If a digest is not provided, this
command will query the registry to determine its value. Either a tag
or a digest is required.

The output is meant to assist enforcement of policies that ensure the
most recent Tekton Bundle is used. As such, each entry contains an
"effective_on" date which is set to 30 days from today. This indicates
the Tekton Bundle usage should be updated within that period.

If --prune is set, on by default, non-acceptable entries are removed.
Any entry with an effective_on date in the future, and the entry with
the most recent effective_on date *not* in the future are considered
acceptable.

[source,shell]
----
ec track bundle [flags]
----

== Examples
Track multiple bundles:

  ec track bundle --bundle <IMAGE1> --bundle <IMAGE2>

Save tracking information into a new tracking file:

  ec track bundle --bundle <IMAGE1> --output <path/to/new/file>

Save tracking information into an image registry:

  ec track bundle --bundle <IMAGE1> --output <oci:registry.io/repository/image:tag>

Extend an existing tracking file with a new bundle:

  ec track bundle --bundle <IMAGE1> --input <path/to/input/file>

Extend an existing tracking file with a new bundle and save changes:

  ec track bundle --bundle <IMAGE1> --input <path/to/input/file> --replace

Extend an existing tracking image with a new bundle and push to an image registry:

  ec track bundle --bundle <IMAGE1> --input <oci:registry.io/repository/image:tag> --replace

Skip pruning for unacceptable entries:

  ec track bundle --bundle <IMAGE1> --input <path/to/input/file> --prune=false

Update existing acceptable bundles:

  ec track bundle --input <path/to/input/file> --output <path/to/input/file> --freshen

== Options

-b, --bundle:: bundle image reference to track - may be used multiple times (Default: [])
--freshen:: resolve image tags to catch updates and use the latest image for the tag (Default: false)
-g, --git:: git references to track - may be used multiple times (Default: [])
-h, --help:: help for bundle (Default: false)
-i, --input:: existing tracking file
-o, --output:: write modified tracking file to a file. Use empty string for stdout, default behavior
-p, --prune:: remove entries that are no longer acceptable, i.e. a newer entry already effective exists (Default: true)
-r, --replace:: write changes to input file (Default: false)

== Options inherited from parent commands

--debug:: same as verbose but also show function names and line numbers (Default: false)
--kubeconfig:: path to the Kubernetes config file to use
--quiet:: less verbose output (Default: false)
--timeout:: max overall execution duration (Default: 5m0s)
--trace:: enable trace logging (Default: false)
--verbose:: more verbose output (Default: false)

== See also

 * xref:ec_track.adoc[ec track - Record resource references for tracking purposes]
