apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/enterprise-contract/ec-cli?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    # Only rebuild the task bundle if there is a change to the task definition
    pipelinesascode.tekton.dev/on-cel-expression: >-
      event == "pull_request" && target_branch == "main" && "tasks/verify-enterprise-contract/0.1/verify-enterprise-contract.yaml".pathChanged()
    pipelinesascode.tekton.dev/pipeline: ".tekton/task-build.yaml"
  labels:
    appstudio.openshift.io/application: ec-main-task-build
    appstudio.openshift.io/component: task-main
    pipelines.appstudio.openshift.io/type: build
  name: task-main-on-pull-request
  namespace: rhtap-contract-tenant
spec:
  # Note that some params here are not used since the build-container
  # task is tkn-bundle rather than buildah
  params:
    - name: dockerfile
      value: Dockerfile
    - name: git-url
      value: '{{source_url}}'
    - name: image-expires-after
      value: 5d
    - name: output-image
      value: quay.io/redhat-user-workloads/rhtap-contract-tenant/ec-main-task-build/task-main:on-pr-{{revision}}
    - name: path-context
      value: .
    - name: revision
      value: '{{revision}}'
  pipelineRef:
    name: task-build
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
