.nh
.TH "EC-COMPLETION" "1" "Jul 2022" "" ""

.SH NAME
.PP
ec-completion - Generate the autocompletion script for the specified shell


.SH SYNOPSIS
.PP
\fBec completion [flags]\fP


.SH DESCRIPTION
.PP
Generate the autocompletion script for ec for the specified shell.
See each sub-command's help for details on how to use the generated script.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for completion


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--debug\fP[=false]
	same as verbose but also show function names and line numbers

.PP
\fB--quiet\fP[=false]
	less verbose output

.PP
\fB--verbose\fP[=false]
	more verbose output


.SH SEE ALSO
.PP
\fBec(1)\fP, \fBec-completion-bash(1)\fP, \fBec-completion-fish(1)\fP, \fBec-completion-powershell(1)\fP, \fBec-completion-zsh(1)\fP
