.nh
.TH "EC-COMPLETION-FISH" "1" "Jul 2022" "" ""

.SH NAME
.PP
ec-completion-fish - Generate the autocompletion script for fish


.SH SYNOPSIS
.PP
\fBec completion fish [flags]\fP


.SH DESCRIPTION
.PP
Generate the autocompletion script for the fish shell.

.PP
To load completions in your current shell session:

.PP
.RS

.nf
ec completion fish | source

.fi
.RE

.PP
To load completions for every new session, execute once:

.PP
.RS

.nf
ec completion fish > ~/.config/fish/completions/ec.fish

.fi
.RE

.PP
You will need to start a new shell for this setup to take effect.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for fish

.PP
\fB--no-descriptions\fP[=false]
	disable completion descriptions


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--debug\fP[=false]
	same as verbose but also show function names and line numbers

.PP
\fB--quiet\fP[=false]
	less verbose output

.PP
\fB--verbose\fP[=false]
	more verbose output


.SH SEE ALSO
.PP
\fBec-completion(1)\fP
