.nh
.TH "EC-DOCS" "1" "Jul 2022" "" ""

.SH NAME
.PP
ec-docs - Generate documentation


.SH SYNOPSIS
.PP
\fBec docs [flags]\fP


.SH DESCRIPTION
.PP
Generates the documentation in multiple formats.
    Specify the target directory by adding the --docs-dir argument.


.SH OPTIONS
.PP
\fB--docs-dir\fP="docs"
	Target directory for the generated documentation.

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for docs


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--debug\fP[=false]
	same as verbose but also show function names and line numbers

.PP
\fB--quiet\fP[=false]
	less verbose output

.PP
\fB--verbose\fP[=false]
	more verbose output


.SH EXAMPLE
.PP
.RS

.nf

    ec docs
    ec docs --docs-dir /some/other/location
    

.fi
.RE


.SH SEE ALSO
.PP
\fBec(1)\fP
