.nh
.TH "EC-SIGN-OFF" "1" "Jul 2022" "" ""

.SH NAME
.PP
ec-sign-off - Capture signed off signatures from a source (github repo, Jira)


.SH SYNOPSIS
.PP
\fBec sign-off [flags]\fP


.SH DESCRIPTION
.PP
Supported sign off sources are commits captured from a git repo and jira issues.
               The git sources return a signed off value and the git commit. The jira issue is
			   a TODO, but will return the Jira issue with any sign off values.


.SH OPTIONS
.PP
\fB-f\fP, \fB--file-path\fP=""
	Path to ApplicationSnapshot JSON file

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for sign-off

.PP
\fB--image-ref\fP=""
	The OCI repo to fetch the attestation from.

.PP
\fB-j\fP, \fB--json-input\fP=""
	ApplicationSnapshot JSON string

.PP
\fB--public-key\fP=""
	Public key


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--debug\fP[=false]
	same as verbose but also show function names and line numbers

.PP
\fB--quiet\fP[=false]
	less verbose output

.PP
\fB--verbose\fP[=false]
	more verbose output


.SH SEE ALSO
.PP
\fBec(1)\fP
