.nh
.TH "EC-VALIDATE" "1" "Jul 2022" "" ""

.SH NAME
.PP
ec-validate - Provides validation of various object


.SH SYNOPSIS
.PP
\fBec validate [flags]\fP


.SH DESCRIPTION
.PP
TODO


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for validate


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--debug\fP[=false]
	same as verbose but also show function names and line numbers

.PP
\fB--quiet\fP[=false]
	less verbose output

.PP
\fB--verbose\fP[=false]
	more verbose output


.SH SEE ALSO
.PP
\fBec(1)\fP, \fBec-validate-image(1)\fP, \fBec-validate-pipeline(1)\fP
