.nh
.TH "EC-VALIDATE-IMAGE" "1" "Jul 2022" "" ""

.SH NAME
.PP
ec-validate-image - Validates container image conformance with the Enterprise Contract


.SH SYNOPSIS
.PP
\fBec validate image [flags]\fP


.SH DESCRIPTION
.PP
Validates image signature, signature of related artifacts such as build
attestation signature, transparency logs for the image signature and releated
artifacts, gathers build related data and evaluates the enterprise policy
against it.


.SH OPTIONS
.PP
\fB-f\fP, \fB--file-path\fP=""
	Path to ApplicationSnapshot JSON file

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for image

.PP
\fB-i\fP, \fB--image\fP=""
	Image reference

.PP
\fB-j\fP, \fB--json-input\fP=""
	ApplicationSnapshot JSON string

.PP
\fB-o\fP, \fB--output-file\fP=""
	Path to output file

.PP
\fB-p\fP, \fB--policy\fP="ec-policy"
	Policy configuration name

.PP
\fB-k\fP, \fB--public-key\fP=""
	Public key

.PP
\fB-r\fP, \fB--rekor-url\fP="https://rekor.sigstore.dev/"
	Rekor URL

.PP
\fB-s\fP, \fB--strict\fP[=false]
	Enable strict mode


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--debug\fP[=false]
	same as verbose but also show function names and line numbers

.PP
\fB--quiet\fP[=false]
	less verbose output

.PP
\fB--verbose\fP[=false]
	more verbose output


.SH EXAMPLE
.PP
.RS

.nf
Validate single image "registry/name:tag" with the default policy defined in
the EnterpriseContractPolicy custom resource named "ec-policy" in the current
Kubernetes namespace:

  ec validate image --image registry/name:tag

Validate an application snapshot provided by the ApplicationSnapshot custom
resource provided via a file using a custom public key and a private Rekor
instance in strict mode:

ec validate image --file-path my-app.yaml --public-key my-key.pem --rekor-url https://rekor.example.org --strict

.fi
.RE


.SH SEE ALSO
.PP
\fBec-validate(1)\fP
