.nh
.TH "EC" "1" "Jul 2022" "" ""

.SH NAME
.PP
ec - Tool to enforce enterprise contracts


.SH SYNOPSIS
.PP
\fBec [flags]\fP


.SH DESCRIPTION
.PP
TODO: description


.SH OPTIONS
.PP
\fB--debug\fP[=false]
	same as verbose but also show function names and line numbers

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for ec

.PP
\fB--quiet\fP[=false]
	less verbose output

.PP
\fB--verbose\fP[=false]
	more verbose output


.SH SEE ALSO
.PP
\fBec-completion(1)\fP, \fBec-docs(1)\fP, \fBec-replace(1)\fP, \fBec-sign-off(1)\fP, \fBec-track(1)\fP, \fBec-validate(1)\fP, \fBec-version(1)\fP
